---
- name: istall apache, open ports 80, 443 and copy index.html to webserver
  hosts: all
  become: yes

  vars:
   source_file: ./index.html
   destin_file: /var/www/html/index.html
  tasks:
  - name: install apache web server
    yum: name=httpd state=latest

  - name: copy index.html to webservers
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555

  - name: start webserver and make it enable on boot
    service: name=httpd state=started enabled=yes
  
  - name: start firewalld
    service: name=firewalld state=started

  - name: open port 80
    firewalld:
      port: 80/tcp
      immediate: yes
      permanent: true
      state: enabled

  - name: open port 443
    firewalld:
      port: 443/tcp
      immediate: yes
      permanent: true
      state: enabled
